OroCampo.WebSite/Controllers/BlogPostsController.cs
using System.Configuration;
using System.Threading.Tasks;
using OroCampo.DatabaseHandler.Helpers;
using OroCampo.WebSite.Models.BlogPosts;

namespace OroCampo.WebSite.Controllers
{
    using System.Web.Mvc;

    public class BlogPostsController : Controller
    {
        // GET: BlogPosts
        public async Task<ActionResult> Index()
        {
            var blogPosts =
                await DatabaseHelper.GetBlogPosts(ConfigurationManager.AppSettings["ConnectionString"], true);
            IndexModel model = new IndexModel()
            {
                BlogPosts = blogPosts
            };
            return View(model);
        }
    }
}

OroCampo.WebSite/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OroCampo.WebSite.Controllers
{
    using System.Configuration;
    using System.Threading.Tasks;

    using OroCampo.WebSite.Models;

    public class LayoutController : Controller
    {
        // GET: Layout
        public ActionResult GetProducts()
        {
            return View();
        }

        public async Task<ActionResult> GetServices()
        {
            var services = await DatabaseHandler.Helpers.DatabaseHelper.GetServices(
                ConfigurationManager.AppSettings["ConnectionString"],
                false);

            return this.View(new LayoutServicesModel() { Services = services });
        }
    }
}

OroCampo.WebSite/Controllers/PhotosController.cs
namespace OroCampo.WebSite.Controllers
{
    using System.Web.Mvc;

    public class PhotosController : Controller
    {
        // GET: Photos
        public ActionResult Index()
        {
            return View();
        }
    }
}

OroCampo.WebSite/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OroCampo.WebSite.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index()
        {
            return View();
        }
    }
}

OroCampo.WebSite/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OroCampo.WebSite.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult Index()
        {
            return View();
        }
    }
}

OroCampo.WebSite/Views/Shared/CheckIfAuthenticated.cshtml
@{
    ViewBag.Title = "CheckIfAuthenticated";
}

@if (!Request.IsAuthenticated)
{
   Response.Redirect("~/Home/Index");
}

OroCampo.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">
    <link rel="icon" type="image/png" href="~/Theme/img/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="~/Theme/img/favicon-16x16.png" sizes="16x16" />
    <link rel="shortcut icon" href="~/Theme/img/favicon.ico">
    @Styles.Render("~/Content/texteditorcss")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/theme")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0 8px 16px 0 #000000;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .dropdown-content a:hover {
                    background-color: #f1f1f1
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }
    </style>
</head>
<body>
    <!--================Header Area =================-->
    <header class="main_header_area">
        <div class="header_top">
            <div class="container">
                <div class="header_top_inner">
                    <div class="pull-left">
                        <a href=""><i class="fa fa-phone"></i> Τηλ 1: <b>23410 - 27288</b>  &nbsp;  Τηλ 2: <b>23410 - 500980 </b>  &nbsp;  Τηλ 3: <b>23410 - 20111</b></a>
                        <a href="~/Home/Contact"><i class="fa fa-envelope-o"></i>info@OroCampo.gr</a>

                    </div>
                    <div class="pull-right">
                        <ul class="header_social">
                            <li><a href="https://www.facebook.com/OROCAMPO/?tn-str=k*F"><i class="fa fa-facebook"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="header_menu">
            <nav class="navbar navbar-default">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="~/Home/index"><img src="~/Theme/img/white_logo.png" alt=""></a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">

                            <li>@Html.ActionLink("Αρχικη", "Index", "Home")</li>

                            <li>@Html.ActionLink("Σχετικα", "About", "Home")</li>

                            <li class="submenu dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Υπηρεσιες <i class="fa fa-angle-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Όλες υπηρεσίες", "Index", "Services")</li>
                                    @*@{ Html.Action("GetServices", "Layout"); }*@
                                </ul>
                            </li>
                            <li class="submenu dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Προϊοντα <i class="fa fa-angle-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Όλα τα προϊόντα", "Index", "Products")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Αρθρα", "Index", "BlogPosts")</li>
                            <li>@Html.ActionLink("Εικονες", "Index", "Photos")</li>
                            <li>@Html.ActionLink("Επικοινωνια", "Contact", "Home")</li>
                            @if (Request.IsAuthenticated)
                            {
                                <li class="submenu dropdown">
                                    <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Διαχειρηση <i class="fa fa-angle-down"></i></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Προσθήκη κατηγορίας φωτογραφίας", "ManagementPhotoCategory", "Admin")</li>
                                        <li>@Html.ActionLink("Προσθήκη κατηγορίας προϊόντος", "ManagementProductCategory", "Admin")</li>
                                        <li>@Html.ActionLink("Προσθήκη προϊόντος", "ManagementProduct", "Admin")</li>
                                        <li>@Html.ActionLink("Προσθήκη φωτογραφίας", "ManagementPhoto", "Admin")</li>
                                        <li>@Html.ActionLink("Προσθήκη υπηρεσίας", "ManagementService", "Admin")</li>
                                        <li>@Html.ActionLink("Προσθήκη άρθρου", "ManagementBlogPost", "Admin")</li>
                                        @Html.Partial("_LoginPartial")
                                    </ul>
                                </li>
                            }
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </div>
    </header>
    @RenderBody()

    <!--================Footer Area =================-->
    <section class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <div class="footer_left_text">
                        <h3>Oro Campo</h3>
                        <p>
                            Για οποιαδήποτε πληροφορία επικοινονίστε μαζί μας<br> 
                            μέσω e-mail ή μέσω τηλεφώνου.
                        </p>
                    </div>
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="footer_left_text">
                        <h3>Καλέστε μας στο κεντρικό κατάστημα</h3>
                        <p>23410-27288 <span>ή</span> info@OroCampo.gr</p>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </section>
    <!-- End Footer top section -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-xs-12">
                    <div class="footer_pannel">
                        <h3>Διευθύνσεις Καταστημάτων</h3>
                        <ul>
                            <li>
                                <span><i class="fa fa-map-marker" aria-hidden="true"></i></span>
                                <p>
                                    <b>Κεντρικό κατάστημα :</b> <br/>
                                    Δυτ. επαρχιακή οδός <br/>
                                    Κιλκίς - Μεταλλικού<br/>
                                   <b>Υποκατάστημα Πολυκάστρου :</b><br/>
                                    Μεγ. Αλεξάνδρου & Αγ. Γεωργίου 1
                                </p>
                            </li>
                            <li>
                                <span><i class="fa fa-phone" aria-hidden="true"></i></span>
                                <p>
                                    <b>Κεντρικό κατάστημα :</b><br />
                                    Τηλ / Fax : 23410 - 27288,<br />
                                    Τηλ : 23410 - 500980<br/>
                                    Fax : 23410 - 75009<br />
                                   <b>Υποκατάστημα Πολυκάστρου :</b> <br/>
                                    Τηλ / Fax : 23410 - 20111<br />
                                </p>
                            </li>
                            <li>
                                <span><i class="fa fa-envelope" aria-hidden="true"></i></span>
                                <p>
                                    info@orocampo.gr
                                </p>
                            </li>
                        </ul>
                        <ul class="f_con">
                            <li> <a href="https://www.facebook.com/OROCAMPO/?tn-str=k*F"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
                            @*<li>
                                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                                </li>*@
                        </ul>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12">
                    <div class="footer_logo">
                        <figure>
                            <img src="~/Theme/img/resource/footer_logo.png" alt="">
                        </figure>
                        <p>© Copyright Oro Campo 2019 .</p>
                        <p>All right reserved.</p>
                        <p>Design by Themelab15</p>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12">
                    <div class="footer_pannel " style="padding-left: 30px">
                        <h3>Μενού γρήγορων επιλογών</h3>
                        <ul class="footer_links">
                            <li>@Html.ActionLink("Αρχικη", "Index", "Home")</li>
                            <li>@Html.ActionLink("Σχετικα", "About", "Home")</li>
                            <li>@Html.ActionLink("Υπηρεσίες", "Index", "Services")</li>
                            <li>@Html.ActionLink("Προϊόντα", "Index", "Products")</li>
                            <li>@Html.ActionLink("Αρθρα", "Index", "BlogPosts")</li>
                            <li>@Html.ActionLink("Εικονες", "Index", "Photos")</li>
                            <li>@Html.ActionLink("Επικοινωνια", "Contact", "Home")</li>

                            @*<li><a href="#">Αρχική</a></li>
                                <li><a href="#">Σχετικά με εμάς</a></li>
                                <li><a href="#">Υπηρεσίες</a></li>
                                <li><a href="#">Προϊόντα</a></li>
                                <li><a href="#">Δημοσιεύσεις</a></li>*@
                        </ul>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </footer>
    <!--================End Footer Area =================-->


    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js"></script>
    @Scripts.Render("~/bundles/texteditorjs")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/sitequery")
    @Scripts.Render("~/bundles/buttonchoosefilejs")
    @Scripts.Render("~/bundles/theme")
    @RenderSection("scripts", required: false)
</body>
</html>